version: '3.1'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - phonebook:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py && ./manage.py collectstatic --no-input --clear &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
#    volumes:
#      - ./:/code

volumes:
  phonebook: